DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
go
USE test;

CREATE TABLE cuentas (
 id INT PRIMARY KEY,
 saldo DECIMAL(11,2) CHECK (saldo >= 0)
);

INSERT INTO cuentas VALUES (1, 1000);
INSERT INTO cuentas VALUES (2, 2000);
INSERT INTO cuentas VALUES (3, 0);

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

Begin TRANSACTION;
SELECT SUM(saldo) FROM cuentas;

SELECT SUM(saldo) FROM cuentas;

--2do
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--3ro
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--4to
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
