USE test;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

Begin TRANSACTION;
UPDATE cuentas SET saldo = saldo - 100 WHERE id = 1;

COMMIT;
--2do
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--3ro
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--4to
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
