USE test;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

Begin TRANSACTION;
INSERT INTO cuentas VALUES (4, 3000);

COMMIT;
--2do
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
--3ro
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--4to
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
