USE Prueba
--1
SELECT * FROM ALUM2014

--2
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM2014

--3
SELECT NOMBRE, APELLIDOS FROM ALUM2014
WHERE poblacion='GUADALAJARA'

--4
SELECT DNI,  NOMBRE,  APELLIDOS, CURSO, NIVEL, CLASE, DATEDIFF(YEAR,Fecha_nac,GETDATE()) AS EDAD FROM ALUM2014
ORDER BY APELLIDOS ASC, NOMBRE ASC

--5
SELECT DNI FROM ALUM2014 
WHERE fecha_nac IS NULL

--6
SELECT * FROM ALUM2014
 WHERE fecha_nac IS NOT NULL

--7
SELECT DNI, NOMBRE, APELLIDOS FROM ALUM2014
WHERE APELLIDOS LIKE '%Pérez%'

--8
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM2014
WHERE Poblacion='MARCHAMALO' OR Poblacion='CABANILLAS' OR Poblacion='YUNQUERA'

--9
SELECT DNI, NOMBRE, APELLIDOS, NIVEL, CLASE FROM ALUM2014
WHERE DATEDIFF(YEAR,Fecha_nac,GETDATE()) BETWEEN 17 AND 20

--10
SELECT DNI, NOMBRE, APELLIDOS, NIVEL, (FALTAS1 + FALTAS2 + FALTAS3)/3 AS FALTAS FROM ALUM2014
WHERE NIVEL='ESO' OR NIVEL='ESI'

--11
SELECT * FROM ALUM2014
WHERE FALTAS1 IS NULL OR FALTAS2 IS NULL OR FALTAS3 IS NULL

--12 
SELECT DNI, NOMBRE, APELLIDOS, NIVEL FROM ALUM2014
Where fecha_nac LIKE '1988-03%'

--13
SELECT DNI, CONCAT(NOMBRE,' ', APELLIDOS) AS nombre_apellidos FROM ALUM2014
ORDER BY DNI DESC

--14
SELECT NOMBRE, APELLIDOS FROM ALUM2014
WHERE CURSO=4 AND NIVEL= 'ESO' AND CLASE='B' ORDER BY APELLIDOS, NOMBRE

--15
SELECT NOMBRE, APELLIDOS FROM ALUM2014
WHERE CURSO=4 AND NIVEL= 'ESO' AND CLASE='B' ORDER BY APELLIDOS, NOMBRE ASC

--16
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE, DATEDIFF(yy,fecha_nac,GETDATE()) AS edad FROM ALUM2014
WHERE NIVEL NOT IN ('ESO','BAC') ORDER BY CURSO, NIVEl, CLASE ASC, APELLIDOS DESC;

--17
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE, DATEDIFF(yy,fecha_nac,GETDATE()) AS edad FROM ALUM2014
WHERE NIVEL NOT IN ('ESO','BAC') AND DATEDIFF(yy,fecha_nac,GETDATE()) BETWEEN 20 AND 22 ORDER BY CURSO, NIVEl, CLASE ASC, APELLIDOS DESC;